"""Surface-independent execution contract; no browser-library imports."""

from typing import Protocol

from .policy import Policy


class Surface(Protocol):
    policy: Policy
    session_id: str
    dimensions: tuple[int, int]

    async def start(self) -> None: ...
    async def observe(self, max_age: float = 0.0) -> bytes: ...
    async def click(self, x: float, y: float) -> None: ...
    async def type_text(self, text: str) -> None: ...
    async def key(self, key: str) -> None: ...
    async def scroll(self, delta: float) -> None: ...
    def is_alive(self) -> bool: ...
    async def close(self) -> None: ...
